### ISSUE TITLE
Unable to install with bower

### ISSUE THREAD

**Issue by smarbiv** [KyleAMathews/deepmerge#63]
Hi,
I have an issue with the latest release (1.4.1), it looks like the module uses 'is-mergeable-object' which is missing...

**Comment by macdja38** [comment]
How are you requiring/importing deepmerge?

**Comment by TehShrike** [comment]
Are you using bower?  `is-mergeable-object` isn't on bower...

**Comment by TehShrike** [comment]
I'm not sure exactly what issue you were having, but I published 1.4.3 to inline is-mergeable-object for folks using bower who are trying to bundle the CommonJS entry point.

Let us know what your environment is @smarbiv, and whether or not 1.4.3 works for you.

**Comment by smarbiv** [comment]
Thanks for your quick response.
Yes, we do using  bower and unfortunately the fix didn't solve the problem  because when bringing it with bower the 'is-mergeable-object ' does not included..

**Comment by TehShrike** [comment]
1.4.3 no longer relies on you downloading the is-mergeable-object module - the code is inlined in every version of the file that is distributed on the npm registry.

Does bower not use the npm registry?  Does it require that the built files be on Github?  I'm not familiar with bower's workings at all.

**Comment by TehShrike** [comment]
hmm, at the very least, it looks like I forgot to update the `main` field in the bower.json

**Comment by smarbiv** [comment]
Hi, 
Bower uses tags, downloads the library and uses the main file you defined in your bower.json (in your case this is index.js). But this index.js is from your source code which is not packed with 'is-mergeable-object', so this is the reason why we can't use 'deepmerge' with bower..

**Comment by TehShrike** [comment]
I published 1.4.4 with an updated bower.json, let me know if that works for you.

What bundler are you using?

I didn't think to ask this when Bower was discussed before, but I'm curious what bundlers look at bower.json at all.

**Comment by TehShrike** [comment]
I'll assume everything is fine and dandy now :-)

**Comment by smarbiv** [comment]
Hi,
Sorry for the late response.
Unfortunately it didn't fix the issue.
We use bower to bring the package (using the git endpoint: "deepmerge": "https://github.com/KyleAMathews/deepmerge.git") and webpack for packing.
Because the 'dist' folder does not included in the git, the fix which use 'dist/umd.js' as the main file doesn't work for me.
Meanwhile we are using an older version of your module (#1.3.2)

**Comment by TehShrike** [comment]
Could you depend on the unpkg link?  https://unpkg.com/deepmerge/dist/umd.js

**Comment by smarbiv** [comment]
Yes, that works for me! :)
Thank you very much for all your help!

**Comment by TehShrike** [comment]
I wonder if there's something I could put in the bower.json that would save other bower users from running into this

**Comment by smarbiv** [comment]
Your fix in 1.4.4 could work if the file was exists, so adding the dist folder with the umd.js file to git maybe could be a solution..

**Comment by TehShrike** [comment]
Is bower support worth adding build artifacts to the repository?

**Comment by TehShrike** [comment]
I'm leaning towards no :-x

**Comment by TehShrike** [comment]
Merging #69 will officially drop Bower support.
